### ISSUE TITLE
Install Instruction and Tutorial 404 not found

### ISSUE THREAD

**Issue by YichenGong** [tomdoel/pulmonarytoolkit#18]
Install Instruction and Tutorial 404 not found

**Comment by kleinfeld** [comment]
have a look in the folder 'Documentation'

or click here:

https://github.com/tomdoel/pulmonarytoolkit/tree/master/Documentation

hope this was helpful?

**Comment by tomdoel** [comment]
Thanks @kleinfeld

**Comment by tomdoel** [comment]
Thanks for opening the issue @YichenGong . I will update the links - they were pointing to Google Code which has shut down

**Comment by tomdoel** [comment]
Links updated in v0.7
