### ISSUE TITLE
erroring when clicked the coronal analysis,sagittial analysis ,axial analysis button

### ISSUE THREAD

**Issue by saaffjf** [tomdoel/pulmonarytoolkit#58]
First of all, thank you for providing the software. I made the following error when I clicked the coronal analysis button while running: The plugin PTKSaveCoronalAnalysisResults failed with the following error: The unidentified field name is called "SetPreferredOrientation".; Exception message: The unidentified field name is "SetPreferredOrientation".: PTKDivideLungsIntoCoronalBins.RunPlugin(can you help me,thanks) @tomdoel.

**Comment by saaffjf** [comment]
![mmexport1687682184734](https://github.com/tomdoel/pulmonarytoolkit/assets/137113459/1762f4ef-d141-4401-bcae-bad7408f6529)

**Comment by tomdoel** [comment]
Hi @saaffjf, thanks for reporting this. I have identified the issue and added a likely fix into the dev branch. 
I'm not able to test this just now but when I can I will merge into the main branch.

In the meantime you can try checking out the dev branch and seeing if that fixes the issue.

Thanks
